### ISSUE TITLE
Remove Google analytics

### ISSUE THREAD

**Issue by omkarkhair** [vasanthv/hello#16]
The `index.html` has a Google analytics tracker, and it would be a good idea to either remove it, or have a config without a key.

It opens a can of privacy worms if someone inadvertently creates a private deployments and the URLs keep getting tracked.

**Comment by vasanthv** [comment]
Fixed it. https://github.com/vasanthv/hello/commit/42925f6d1423c295de0fe2d928c362df17aaf371
