### ISSUE TITLE
How to add custom/self host TURN server?

### ISSUE THREAD

**Issue by hassaan-dev** [vasanthv/hello#25]
How to add custom/self host TURN server?

on `index.html`

I tried to put own Turn Server in following format, but this is not working

	var ICE_SERVERS = [
		{ 'urls': 'stun:stun.l.google.com:19302' },
		{ 'urls': 'stun:stun.stunprotocol.org:3478' },
		{ 'urls': 'stun:stun.sipnet.net:3478' },
		{ 'urls': 'stun:stun.ideasip.com:3478' },
		{ 'urls': 'stun:stun.iptel.org:3478' },
		{ 'urls': ['turn:myturn.com:3478'],'username':'123','credential':'123'}
	];

**Comment by vasanthv** [comment]
@hassaan-dev Please check this https://stackoverflow.com/questions/26342589/how-does-webrtc-decide-which-turn-servers-to-use

**Comment by hassaan-dev** [comment]
@vasanthv I have tested TURN server via https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

I just need to know, is my above format is OK or NOT

2nd thing, When I open https://itshello.co/ this redirect to random URL like `https://itshello.co/2k1bmi`
How can I redirect in the same way?

**Comment by vasanthv** [comment]
@hassaan-dev 
1. The format seems ok to me as per MDN https://developer.mozilla.org/en-US/docs/Web/API/RTCIceServer/urls

2. It is not an actual redirection, but just the URL change. You can do it the same way as it is done in this line
https://github.com/vasanthv/hello/blob/master/index.html#L59

**Comment by hassaan-dev** [comment]
Thank you @vasanthv for quick response
I am currently deploying this on this URL https://hello.saedhamdan.com:3000/
Redirection is not working, can you please have a look? 

2nd Turn Server is also in same error. Video is not working if network is not same.

If I post logs from `about:webrtc` that will helpful for you to debug the issue?

**Comment by vasanthv** [comment]
I see the pushState error. You are trying to push https://hello.saedhamdan.com/blah from  https://hello.saedhamdan.com:3000/. It will get rejected as the Origin is different. If the Room ID is not present it can mess many things. So can you fix that first.

**Comment by hassaan-dev** [comment]
@vasanthv I resolve the `pushState` error
This was cause of port at end of URL. I think this is enhancement in code to make it work with PORT is URL.
anyways please try this link now, https://hello.saedhamdan.com/s0pggj

**Comment by vasanthv** [comment]
@hassaan-dev Yes. Now PushState is fixed and the video is working fine for me. 
I guess you haven't enabled autoplay of the video in Chrome. It wont play the video immediately, you need to enable autoplay for it to work.

**Comment by hassaan-dev** [comment]
Do you see me in video? the other person's video does not work if he/she is using other network.

This is working fine when both persons are using same network

**Comment by vasanthv** [comment]
@hassaan-dev It seems to work fine for me. 
I tried one in a Wifi & another in my mobile (4G network). https://www.dropbox.com/s/dwz40nfcvkf9jaa/Screenshot%202019-03-07%2014.26.10.png?dl=0

May be your ISP is messing up or something.

**Comment by hassaan-dev** [comment]
Thanks @vasanthv once again
Okay, I will check this and update the solution or actual problem here to help other people if some someone face the same issue
