### ISSUE TITLE
Custom Room ID

### ISSUE THREAD

**Issue by hassaan-dev** [vasanthv/hello#26]
Hi,
When I open `hello` demo site, this automatically redirect to random URL. Instead of random URL

I want user to enter custom ROOM ID / URL

Can you please help me with this?

**Comment by vasanthv** [comment]
You should get the ROOM-ID from the user somehow and then initiate the code starting from here https://github.com/vasanthv/hello/blob/master/index.html#L78 

You could wrap all those lines in a separate function and initiate them when you have the room-id.
